### ISSUE TITLE
Missing content in pdf

### ISSUE THREAD

**Issue by nickedes** [dufferzafar/geeksforgeeks.pdf#3] opened 2016-07-13 09:35 UTC
For example in the `Dynamic Programming.pdf` on page no. 111
![selection_001](https://cloud.githubusercontent.com/assets/5887656/16798592/6fcb28fc-490a-11e6-8c63-0350a7580028.png)

In the first para some content is missing when you compare from  [here](http://www.geeksforgeeks.org/dynamic-programming-set-20-maximum-length-chain-of-pairs/).
I saw similar problem in some other pages too. :stuck_out_tongue_winking_eye:

**Comment by dufferzafar** [comment] 2016-07-13 09:38
Hm. That's weird.

**Comment by dufferzafar** [comment] 2018-06-14 08:42
@mzfr Look into why this is happening. ASAP. Shaam tak mil jana chaiye.

**Comment by iCHAIT** [comment] 2018-06-14 08:45
LoL

**Comment by nickedes** [comment] 2018-09-29 19:07
@dufferzafar Haa bhaiya :joy: :stuck_out_tongue_closed_eyes:

**Comment by dufferzafar** [comment] 2018-09-29 19:13
@nickedes Tum toh chup hi raho. Tumhein bas issue banane hain logon ki repo pe. Saara kaam aur logon se karwate ho. Fir seedhe PDF download karke, kamre mein ghus ke padhai karte ho. Aur 10 pointer laate ho. Besharam.

**Comment by mzfr** [comment] 2018-09-30 04:13
@dufferzafar aap jis vyakti se sampark karna chahte hai vo iss samme busy hai kuch mahino baad phir khoshish kare.

**Comment by dufferzafar** [comment] 2018-09-30 05:35
Batao kaise ehsaan faramosh log hain dunia mein.

@ichait dekh le bhai. jis ladke ko haath pakad ke git init karna sikhaya, wo aaj mahino baad ki appointment de raha hai.

**Comment by iCHAIT** [comment] 2018-09-30 05:50
@dufferzafar Yehi jeevan ka dastoor h bhai

Koi ni agle saal fir GSoC hona h...!! 😈😈

**Comment by dufferzafar** [comment] 2018-10-03 12:34
This issue has been fixed in the new set of PDFs. My guess is this was being caused by shitty boilerpipy parsing, which has now been replaced with manual based cleaning.

**Closed by dufferzafar** 2018-10-03 12:34 UTC
